
services:
  router:
    image: redirect-server-image
    build: src/router
    depends_on:
      - wdl-container
      - top-moves-container
      - move-analysis-container
    environment:
      - HOST_URL=router-internal
    ports:
      - "8000:8000"

  wdl-container:
    image: wdl-image
    build: src/lambdas/wdl
    ports:
      - "8081:8080"
    volumes:
      - ./assets:/app/assets
    environment:
      - LOCAL_DEV=true
      - TIME_LIMIT=1.0
      - HASH_SIZE=128
      - STOCKFISH_PATH=/var/task/assets/stockfish_linux
    entrypoint: []
    command: ["python", "wdl.py"]

  top-moves-container:
    image: top-moves-image
    build: src/lambdas/top_moves
    ports:
      - "8082:8080"
    environment:
      - LOCAL_DEV=true
      - DEPTH=6
      - HASH_SIZE=128
      - STOCKFISH_PATH=/var/task/assets/stockfish_linux
    entrypoint: []
    command: ["python", "top_moves.py"]

  move-analysis-container:
    image: move-analysis-image
    build: src/lambdas/move_analysis
    ports:
      - "8083:8080"
    volumes:
      - ./assets:/app/assets
    environment:
      - LOCAL_DEV=true
      - DEPTH=6
      - HASH_SIZE=64
      - STOCKFISH_PATH=/var/task/assets/stockfish_linux
    entrypoint: []
    command: ["python", "move_analysis.py"]
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g

